### ISSUE TITLE
put screen shots and screen recording on youtube so we can see the app before installing :)

### ISSUE THREAD

**Issue by ddublon** [AzeezDa/jorno#1]

**Comment by AzeezDa** [comment]
Hello! Thank you for your suggestion. I have now added a link to a YouTube video demonstrating the application. Regarding the screenshots, they are available under the [Images subsection of the Demonstration section of the README](https://github.com/AzeezDa/jorno?tab=readme-ov-file#images). They can be viewed by toggling the toggle list items.

**Comment by ddublon** [comment]
its still not clear its a video , if you can do something like this so that it looks like a video and then the user press play it directs him into youtube its more intuitive 
![image](https://github.com/user-attachments/assets/f2d1756b-fa74-4d2f-bbae-647dc476155f)

**Comment by ddublon** [comment]
this screen shot thing is new to me thank you for teaching me something new

**Comment by ddublon** [comment]
for the expand

**Comment by AzeezDa** [comment]
Hello! Thank you for your feedback and suggestions.

> its still not clear its a video , if you can do something like this so that it looks like a video and then the user press play it directs him into youtube its more intuitive

I have now replaced the old thumbnail in the README with another that includes video-like features. I hope it is now clearer that it links to a video.
